# Generated by Django 4.1.2 on 2022-11-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("EndingIn", models.SmallIntegerField()),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("Visa", "Visa"),
                            ("MasterCard", "MasterCard"),
                            ("American_Express", "American Express"),
                            ("Discover", "Discover"),
                            ("Interlink", "Interlink"),
                            ("STAR", "STAR"),
                            ("JCB", "JCB"),
                        ],
                        help_text="amount currently in the account stated",
                        max_length=30,
                    ),
                ),
                (
                    "Balance",
                    models.BigIntegerField(
                        help_text="amount currently in the account stated"
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        help_text="type of account e.g checking debit ...",
                        max_length=32,
                    ),
                ),
                ("Added_on", models.DateField()),
                ("is_active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=128, unique=True)),
                ("start_Date", models.DateField()),
                ("target_Date", models.DateField()),
                ("Budgeted_Amount", models.BigIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "currency_name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payee",
            fields=[
                ("PayeeID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("Last_trans_date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("Recurring", "Recurring"), ("One_time", "One time")],
                        default="One_time",
                        max_length=32,
                    ),
                ),
                ("repeats_on", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("PaymentID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=128)),
                ("Amount", models.IntegerField()),
                (
                    "Budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.budget"
                    ),
                ),
                (
                    "Payee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.payee"
                    ),
                ),
                (
                    "Schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.schedule"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.category"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.currency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=32)),
                ("amount", models.BigIntegerField()),
                ("date_received", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.currency"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.category"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.currency"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.currency"
            ),
        ),
    ]
